# Generated by Django 2.1.7 on 2019-03-31 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterHashtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('like_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('hashtags', models.ManyToManyField(blank=True, to='insights_twitter.TwitterHashtag')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('screen_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_twitter.TwitterUser'),
        ),
    ]
