# Generated by Django 2.1.7 on 2019-03-31 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramHashtag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('CAROUSEL', 'CAROUSEL'), ('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO')], max_length=32)),
                ('like_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('hashtags', models.ManyToManyField(blank=True, to='insights_instagram.InstagramHashtag')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('follower_count', models.IntegerField()),
                ('media_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_instagram.InstagramUser'),
        ),
    ]
